<?php
    /** Config Info */
    $config = Zend_Registry::get('config');

    /** Set <link /> Tags */
    $this->headLink()->setSeparator('')
        /** @link http://meyerweb.com/eric/tools/css/reset/ */
        ->appendStylesheet('/css/reset.css', 'all')
        /** @link http://html5boilerplate.com/ */
        ->appendStylesheet('/css/html5boilerplate.css', 'all');

    /** Set <meta /> Tags */
    $this->headMeta()->setSeparator('')
        ->appendName('author', $config->site->author)
        ->appendName('description', $config->site->description);

    /** Set <script /> Tags */
    $this->jQuery()
        /** @link http://www.modernizr.com/ */
        ->addJavascriptFile('/js/modernizr-'.$config->modernizr->version.'.min.js');

    if (APPLICATION_ENV == 'production') {
        $this->jQuery()
            ->setVersion($config->jQuery->version)
            /** @link http://mathiasbynens.be/notes/async-analytics-snippet */
            ->addJavascript(
                "var _gaq=[['_setAccount','{$config->google->key->analytics}'],['".
                "_trackPageview']];(function(d,t){var g=d.createElement(t),s=d.ge".
                "tElementsByTagName(t)[0];g.async=1;g.src='//www.google-analytics".
                ".com/ga.js';s.parentNode.insertBefore(g,s)}(document,'script'))"
            );
    } else {
        $this->jQuery()
            ->setLocalPath($this->baseUrl('js/jquery-'.$config->jQuery->version.'.min.js'));
    }

    /** Set <title /> Tag */
    $this->headTitle($config->site->title)->setSeparator('');

    /** Create Document */
    $this->headMeta()->setCharset('UTF-8');
    echo '<?xml version="1.0" encoding="UTF-8"?>'.PHP_EOL.
        ((IS_XHR) ? '' : $this->doctype().PHP_EOL).
        '<html xmlns="http://www.w3.org/1999/xhtml" class="no-js">';

    echo '<head>'.
            $this->headTitle().
            $this->headMeta().
            $this->headLink().
            $this->jQuery().
        '</head><body>'.
            $this->partial('partials/header.phtml', array('site' => $config->site)).
            $this->layout()->content.
            $this->partial('partials/footer.phtml', array('site' => $config->site)).
        '</body></html>';
