<?php
    /** Config Info */
    $config = Zend_Registry::get('config');

    /** Set <link /> Tags */
    $this->headLink()->setSeparator('')
        /** @link http://meyerweb.com/eric/tools/css/reset/ */
        ->appendStylesheet('/css/reset.css', 'all')
        /** @link http://html5boilerplate.com/ */
        ->appendStylesheet('/css/html5boilerplate.css', 'all');

    /** Set <meta /> Tags */
    $this->headMeta()->setSeparator('')
        ->setCharset('UTF-8')
        ->appendName('author', $config->site->author)
        ->appendName('description', $config->site->description);

    /** Set <script /> Tags */
    $this->jQuery()
        /** @link http://www.modernizr.com/ */
        ->addJavascriptFile('/js/modernizr-1.7.min.js');

    /** @link http://mathiasbynens.be/notes/async-analytics-snippet */
    if (APPLICATION_ENV == 'production') {
        $this->jQuery()->addJavascript(
        	"var _gaq=[['_setAccount','{$config->google->key->analytics}'],['".
            "_trackPageview']];(function(d,t){var g=d.createElement(t),s=d.ge".
            "tElementsByTagName(t)[0];g.async=1;g.src='//www.google-analytics".
            ".com/ga.js';s.parentNode.insertBefore(g,s)}(document,'script'))"
        );
    }

    /** Set <title /> Tag */
    $this->headTitle($config->site->title)->setSeparator('');

    /** Create Document */
    if (!$this->doctype()->isXhtml()) {
        echo strtolower($this->doctype()).PHP_EOL.
        	'<html class="no-js" lang="en">';
    } else {
        echo '<?xml version="1.0" encoding="UTF-8"?>'.PHP_EOL.
        	'<html xmlns="http://www.w3.org/1999/xhtml" class="no-js">';
    }

    echo '<head>'.
            $this->headTitle().
            $this->headMeta().
            $this->headLink().
            $this->jQuery().
        '</head><body>'.
            $this->partial('partials/header.phtml').
            $this->layout()->content.
            $this->partial('partials/footer.phtml').
        '</body></html>';
