<?php
    /** Config Info */
    $config = Zend_Registry::get('config');

    /** Set <link /> Tags */
    $this->headLink()->setSeparator('')
        ->prependStylesheet('/css/reset.css?v=2', 'all');

    /** Set <meta /> Tags */
    $this->headMeta()->setSeparator('')
        ->setCharset('UTF-8')
        ->appendName('author', $config->meta->author)
        ->appendName('description', $config->meta->description);

    /** Set <script /> Tags */
    $this->headScript()->setSeparator('')
        /** @link http://www.modernizr.com/ */
        ->appendFile('/js/modernizr-1.7.min.js')
        /** @link http://mathiasbynens.be/notes/async-analytics-snippet */
        ->appendScript("var _gaq=[['_setAccount','{$config->google->key->analytics}'],['_trackPageview']];(function(d,t){var g=d.createElement(t),s=d.getElementsByTagName(t)[0];g.async=1;g.src='//www.google-analytics.com/ga.js';s.parentNode.insertBefore(g,s)}(document,'script'))");

    /** Set <title /> Tag */
    $this->headTitle($config->meta->site->title)->setSeparator('');

    /** Create Document */
    if (!$this->doctype()->isXhtml()) {
        echo strtolower($this->doctype()).PHP_EOL.
        	'<html class="no-js" lang="en">';
    } else {
        echo '<?xml version="1.0" encoding="UTF-8"?>'.PHP_EOL.
        	'<html xmlns="http://www.w3.org/1999/xhtml" class="no-js">';
    }

    echo '<head>'.
            $this->headTitle().
            $this->headMeta().
            $this->headLink().
            $this->headScript().
            $this->jQuery().
        '</head>'.
        '<body>'.
            '<header>'.
            '</header>'.
            $this->layout()->content.
            '<footer>'.
            '</footer>'.
        '</body>'.
        '</html>';
