<?php
    echo '<h1>An error occurred</h1>'.
        '<h2>'.$this->message.'</h2>';

    if (isset($this->exception)) {
        echo '<section><h1>Exception information</h1><p><strong>Message:</strong>'.
            $this->exception->getMessage().'</p><h1>Stack trace</h1><pre>'.
            $this->exception->getTraceAsString().'</pre><h1>Request Parameters</h1><pre>'.
            var_export($this->request->getParams(), true).'</pre></section>';
    }
